name: deploy storybook
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy_storybook.yml
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - .github/workflows/deploy_storybook.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.15.1
      - name: Install Dependencies
        run: npm ci
      - name: clean up storybook-static
        run: |
          DEST_DIR=${{ github.event.pull_request.number }}
          aws s3 rm --recursive \
            s3://${{ secrets.BUCKET_NAME }}/storybook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
      - name: Build storybook
        run: npm run build-storybook
      - name: upload storybook-static
        run: |
          aws s3 cp --recursive \
            ./storybook-static \
            s3://${{ secrets.BUCKET_NAME }}/storybook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
      - name: post preview url to pull-request
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'storybook preview created!!\n' +
                'https://${{ secrets.BUCKET_NAME }}.s3-ap-northeast-1.amazonaws.com/storybook/index.html'
            })
